### ISSUE TITLE
Needed CSS tweaks

### ISSUE THREAD

**Issue by tw2113** [buddypress/developer.buddypress.org#5]
h1 in header needs no float clearing.

**Comment by tw2113** [comment]
Override `p a:hover` border styling with footer links.

**Comment by renatonascalves** [comment]
This is how is appearing here:

![screenshot_1](https://cloud.githubusercontent.com/assets/19148962/15287993/555da288-1b3d-11e6-9593-7602424423f6.png)

**Comment by tw2113** [comment]
Yep, there's going to be needed overrides and decisions for which gets preference....BP site styles or wp-developer theme styles.

**Comment by renatonascalves** [comment]
What about creating a class in the body tag. Something like: bp-developer.

In this way, we could overide the styles only here, without affecting BP pages.

**Comment by tw2113** [comment]
Definitely an option. What I have in place now is mostly a bandaid approach to start getting an idea of the bigger picture. Specifically I'm hotlinking from buddypress.org directly until a permanent solution is in place.

**Comment by tw2113** [comment]
See 93414f4 for the bp-developer body class.
